name: Lint/Test

on:
  pull_request:

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Check formatting
        run: cargo fmt --check
      
      - name: Run clippy
        run: cargo clippy -- -D warnings
      
      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo build

  build-image:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      push: false
      docker-platforms: 'linux/amd64'
